from fpdf import FPDF
from pathlib import Path
from typing import Any
from app.models.schemas import FinalReport
from app.utils.config import logger

class ReportPDF(FPDF):
    def __init__(self, title_text: str, query_text: str):
        super().__init__()
        self.report_title = title_text
        self.report_query = query_text
        self.set_margins(20, 20, 20)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        if self.page_no() > 1:
            self.set_font("helvetica", "B", 8)
            self.set_text_color(79, 70, 229)  # Violet/indigo theme
            self.cell(0, 8, "AI MULTI-AGENT RESEARCH PLATFORM", align="L")
            self.set_font("helvetica", "", 8)
            self.set_text_color(100, 116, 139)
            self.cell(0, 8, f"Topic: {self.report_query[:40]}...", align="R")
            self.ln(10)
            self.draw_grey_line()
            self.ln(5)

    def footer(self):
        if self.page_no() > 1:
            self.set_y(-15)
            self.draw_grey_line()
            self.ln(2)
            self.set_font("helvetica", "I", 8)
            self.set_text_color(100, 116, 139)
            self.cell(0, 10, "Confidential - Generated by AI Research Analyst", align="L")
            self.cell(0, 10, f"Page {self.page_no()}", align="R")

    def draw_grey_line(self):
        self.set_draw_color(226, 232, 240)
        self.set_line_width(0.5)
        self.line(self.l_margin, self.y, self.w - self.r_margin, self.y)

    def render_markdown_block(self, text: str):
        """Simulate basic markdown rendering for headings, lists, bold, and normal text."""
        lines = text.split("\n")
        in_list = False
        
        for line in lines:
            line = line.strip()
            if not line:
                if in_list:
                    in_list = False
                    self.ln(2)
                else:
                    self.ln(4)
                continue

            # Header rendering
            if line.startswith("###"):
                self.ln(2)
                self.set_font("helvetica", "B", 11)
                self.set_text_color(30, 41, 59)
                clean_txt = line.replace("###", "").strip()
                self.multi_cell(0, 6, clean_txt)
                self.set_font("helvetica", "", 10)
                self.set_text_color(71, 85, 105)
                self.ln(2)
            elif line.startswith("##"):
                self.ln(3)
                self.set_font("helvetica", "B", 13)
                self.set_text_color(30, 41, 59)
                clean_txt = line.replace("##", "").strip()
                self.multi_cell(0, 8, clean_txt)
                self.set_font("helvetica", "", 10)
                self.set_text_color(71, 85, 105)
                self.ln(3)
            # List rendering
            elif line.startswith("-") or line.startswith("*"):
                in_list = True
                self.set_font("helvetica", "", 10)
                self.set_text_color(71, 85, 105)
                clean_txt = line[1:].strip()
                # Use bullet point character
                self.cell(6, 6, chr(149), align="C")
                self.multi_cell(0, 6, clean_txt)
            # Normal paragraph
            else:
                if in_list:
                    in_list = False
                    self.ln(2)
                self.set_font("helvetica", "", 10)
                self.set_text_color(71, 85, 105)
                # Parse basic inline bolding **text** -> just output plain or formatted.
                # Since proper inline mixed formatting is complex in fpdf, we output cleaned text.
                clean_line = line.replace("**", "")
                self.multi_cell(0, 6, clean_line)
                self.ln(2)

def generate_report_pdf(report: FinalReport, output_path: Path):
    """Compile PDF file for a FinalReport."""
    pdf = ReportPDF(report.title, report.query)
    
    # ---------------- COVER PAGE ----------------
    pdf.add_page()
    pdf.set_y(40)
    
    # Platform Tag
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(79, 70, 229) # Indigo
    pdf.cell(0, 10, "RESEARCH REPORT & ANALYSIS", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Title
    pdf.set_font("helvetica", "B", 24)
    pdf.set_text_color(15, 23, 42) # Slate-900
    pdf.multi_cell(0, 12, report.title.upper(), align="C")
    pdf.ln(10)
    
    # Divider
    pdf.set_fill_color(79, 70, 229)
    pdf.rect(pdf.w / 2 - 25, pdf.y, 50, 2.5, "F")
    pdf.ln(15)

    # Search Query Information
    pdf.set_font("helvetica", "I", 11)
    pdf.set_text_color(100, 116, 139)
    pdf.multi_cell(0, 6, f"Primary Query: \"{report.query}\"", align="C")
    pdf.ln(40)

    # Metadata Panel
    pdf.set_fill_color(248, 250, 252) # Light blue-grey
    pdf.rect(20, pdf.y, pdf.w - 40, 45, "F")
    
    pdf.set_y(pdf.y + 5)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(79, 70, 229)
    pdf.cell(0, 6, "METADATA PROFILE", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(0, 5, f"Report ID: {report.id}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Date Compiled: {report.created_at}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Integrity Score: {report.validation.overall_integrity_score} / 10.0", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Sources Referenced: {len(report.citations)} unique references", align="C", new_x="LMARGIN", new_y="NEXT")

    # ---------------- EXECUTIVE SUMMARY ----------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.draw_grey_line()
    pdf.ln(5)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 6, report.executive_summary)
    pdf.ln(10)

    # ---------------- REPORT SECTIONS ----------------
    for sec in report.sections:
        pdf.add_page()
        pdf.set_font("helvetica", "B", 16)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 10, sec.title, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        pdf.draw_grey_line()
        pdf.ln(5)
        
        pdf.render_markdown_block(sec.content)
        pdf.ln(5)

    # ---------------- RISKS & CHALLENGES ----------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "Risks & Challenges Assessment", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.draw_grey_line()
    pdf.ln(5)
    
    # Risk Summary
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 6, report.risk_assessment.summary)
    pdf.ln(6)
    
    # Draw table using fpdf2 built-in table manager (handles autowrap and cell height math safely)
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(71, 85, 105)
    
    with pdf.table(col_widths=(25, 72, 73), border=1, line_height=6) as table:
        # Header Row
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(30, 41, 59)
        header_row = table.row()
        header_row.cell("Level")
        header_row.cell("Impact / Threat")
        header_row.cell("Mitigation")
        
        # Data Rows
        for risk in report.risk_assessment.risks:
            row = table.row()
            
            level = risk.level.upper()
            if level == "HIGH":
                pdf.set_text_color(220, 38, 38)
            elif level == "MEDIUM":
                pdf.set_text_color(217, 119, 6)
            else:
                pdf.set_text_color(5, 150, 105)
            
            pdf.set_font("helvetica", "B", 9)
            row.cell(level)
            
            # Reset font and color for description columns
            pdf.set_font("helvetica", "", 9)
            pdf.set_text_color(71, 85, 105)
            row.cell(risk.impact)
            
            mit = risk.mitigation or "No mitigation proposed."
            row.cell(mit)

    # ---------------- VALIDATION & AUDIT ----------------
    pdf.ln(10)
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "Source Validation & Integrity Audit", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.draw_grey_line()
    pdf.ln(5)
    
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.multi_cell(0, 6, f"The report has been verified by the Validator Agent. Overall factual integrity score: {report.validation.overall_integrity_score} / 10.0.")
    pdf.ln(4)
    
    for finding in report.validation.findings:
        type_lbl = finding.finding_type.upper()
        if type_lbl == "CONTRADICTION":
            pdf.set_text_color(220, 38, 38)
        elif type_lbl == "WEAK_EVIDENCE":
            pdf.set_text_color(217, 119, 6)
        else:
            pdf.set_text_color(5, 150, 105)
            
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(0, 6, f"[{type_lbl}] Factual Audit", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(71, 85, 105)
        pdf.multi_cell(0, 6, f"Source: {finding.source}\nAudit Notes: {finding.description}")
        pdf.ln(2)

    # ---------------- CITATION APPENDIX ----------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, "Appendix: Sources & Citations", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.draw_grey_line()
    pdf.ln(5)
    
    for cit in report.citations:
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(79, 70, 229)
        pdf.cell(0, 6, f"[{cit.citation_id}] Source Reference", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_text_color(30, 41, 59)
        source_desc = f"{cit.source_name} ({cit.source_type.upper()})"
        if cit.page:
            source_desc += f" - Page {cit.page}"
        elif cit.url:
            source_desc += f" - URL: {cit.url}"
        
        pdf.multi_cell(0, 6, source_desc)
        pdf.set_font("helvetica", "I", 9)
        pdf.set_text_color(100, 116, 139)
        
        # Clean snippet text for PDF
        snippet_text = cit.snippet.replace("\n", " ").strip()
        if len(snippet_text) > 300:
            snippet_text = snippet_text[:300] + "..."
        pdf.multi_cell(0, 5, f"\"Reference Snippet: {snippet_text}\"")
        pdf.ln(4)

    # Save to disk
    pdf.output(str(output_path))
    logger.info(f"Report PDF generated at: {output_path}")
